CREATE WAREHOUSE DATACO_WH
WITH 
WAREHOUSE_SIZE = "X-SMALL"
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE;

CREATE DATABASE DATACO_DB;
CREATE SCHEMA SUPPLY_CHAIN;
USE SCHEMA SUPPLY_CHAIN;
CREATE STAGE DATACO_STAGE;
CREATE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';
