
 TOP 10 Sales & Profit by Category   
CREATE OR REPLACE VIEW VW_TOP10_CATEGORY_SALES_PROFIT AS
SELECT 
    CATEGORY_NAME,
    SUM(SALES) AS TOTAL_SALES,
    SUM(ORDER_PROFIT_PER_ORDER) AS TOTAL_PROFIT,
    DENSE_RANK() OVER (ORDER BY SUM(SALES) DESC) AS SALES_RANK
FROM DATACO_RAW
GROUP BY CATEGORY_NAME
QUALIFY SALES_RANK <= 10;
   SELECT CATEGORY_NAME,SUM(SALES) AS TOTAL_SALES,
   SUM(ORDER_PROFIT_PER_ORDER) AS TOTAL_PROFIT,
   DENSE_RANK() OVER( ORDER BY SUM(SALES) DESC) AS RANK 
   FROM DATACO_RAW GROUP BY CATEGORY_NAME
   QUALIFY   RANK <= 10 ORDER BY RANK;


Top 10 Products by Sales
CREATE OR REPLACE VIEW Top_10_Products_by_Sales AS
SELECT PRODUCT_NAME,SUM(SALES) AS TOTAL_SALES,DENSE_RANK() OVER(ORDER BY SUM(SALES) DESC) AS RANK FROM DATACO_RAW
GROUP BY PRODUCT_NAME QUALIFY RANK <= 10 ORDER BY RANK;



Top/Bottom Products by Profit
CREATE OR REPLACE VIEW Top_Bottom_Products_by_Profit AS
SELECT 
SUM(ORDER_PROFIT_PER_ORDER) AS TOTAL_PROFIT,
PRODUCT_NAME,
DENSE_RANK() OVER(ORDER BY SUM(ORDER_PROFIT_PER_ORDER) DESC) AS TOP_5,
DENSE_RANK() OVER(ORDER BY SUM(ORDER_PROFIT_PER_ORDER) ASC) AS BOTTOM_5
FROM DATACO_RAW
GROUP BY PRODUCT_NAME QUALIFY TOP_5 <= 5 OR BOTTOM_5 <= 5;

SELECT * FROM Top_Bottom_Products_by_Profit;


Sales vs Profit by Market
CREATE OR REPLACE VIEW Sales_vs_Profit_by_Market AS
SELECT MARKET,
SUM(SALES) AS TOTAL_SALES,
SUM(ORDER_PROFIT_PER_ORDER) AS TOTAL_PROFIT
FROM DATACO_RAW
GROUP BY  MARKET
ORDER BY TOTAL_SALES DESC;




