


CREATE OR REPLACE VIEW Sales_by_Customer_Segment AS
SELECT 
ROUND(SUM(SALES),2) AS TOTAL_SALES,
Customer_Segment
FROM DATACO_RAW
GROUP BY Customer_Segment;

CREATE OR REPLACE VIEW Profit_by_Customer_Segment AS
SELECT
ROUND(SUM(ORDER_PROFIT_PER_ORDER),2) AS TOTAL_PROFIT,
Customer_Segment
FROM
DATACO_RAW
GROUP BY
Customer_Segment;

CREATE OR REPLACE VIEW top_10_country_by_totalsales AS
SELECT 
ROUND(SUM(SALES),2) AS TOTAL_SALES,
Order_Country,
DENSE_RANK() OVER(ORDER BY ROUND(SUM(SALES),2) DESC) as rank
FROM DATACO_RAW 
GROUP BY 
Order_Country qualify rank <= 10;


CREATE OR REPLACE VIEW top_10_customers_by_totalsales AS
SELECT 
ROUND(SUM(SALES),2) AS TOTAL_SALES,
Customer_Id
FROM DATACO_RAW
GROUP BY Customer_Id
ORDER BY TOTAL_SALES DESC LIMIT 10;

CREATE OR REPLACE VIEW CUSTOMER_MARKET_COUNT AS 
SELECT Market,
COUNT(Customer_Id) AS CUSTOMER_COUNT
FROM  DATACO_RAW 
GROUP BY Market;\

CREATE OR REPLACE VIEW  VW_CUSTOMER_MARKET_KPIS_SALES_PER_CUSTOMER AS
SELECT
COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
ROUND(SUM(SALES) / NULLIF(COUNT(DISTINCT CUSTOMER_ID), 0),2)AS SALES_PER_CUSTOMER,
ROUND(COUNT(DISTINCT ORDER_ID) / NULLIF(COUNT(DISTINCT CUSTOMER_ID), 0),2) AS  ORDERS_PER_CUSTOMER,
(SELECT MARKET FROM DATACO_RAW GROUP BY MARKET ORDER BY SUM(SALES) DESC LIMIT 1) AS TOP_MARKET
FROM DATACO_RAW;








