CREATE OR REPLACE  VIEW VW_EXECUTIVE_KPIS AS 
SELECT ROUND(SUM(SALES),2) AS TOTAL_SALES,
ROUND(SUM(ORDER_PROFIT_PER_ORDER),2) AS Total_Profit,
COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
COUNT(DISTINCT CUSTOMER_ID) AS Total_Customers,
SUM(ORDER_ITEM_QUANTITY) AS Total_Quantity_Sold,
ROUND(SUM(SALES)/COUNT(DISTINCT ORDER_ID),2) AS AVG_ORDER_VALUE,
ROUND(SUM(ORDER_PROFIT_PER_ORDER)/COUNT(DISTINCT ORDER_ID),2) AS Average_Profit_per_Order,
ROUND(AVG(ORDER_ITEM_DISCOUNT_RATE),2) AS Average_Discount_Rate,
ROUND((SUM(ORDER_PROFIT_PER_ORDER)/SUM(SALES)) * 100,2) AS Profit_Margin_PERCENT
FROM DATACO_RAW;



CREATE OR REPLACE VIEW VW_SALES_TREND AS 
SELECT
ORDER_YEAR,
ORDER_QUARTER,
ORDER_MONTH,
ROUND(SUM(SALES),2) AS TOTAL_SALES,
ROUND(SUM(ORDER_PROFIT_PER_ORDER),2) AS Total_Profit,
COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
SUM(ORDER_ITEM_QUANTITY) AS Total_Quantity_Sold
FROM DATACO_RAW GROUP BY ORDER_YEAR,ORDER_QUARTER,ORDER_MONTH;



CREATE OR REPLACE VIEW VW_CUSTOMER_ANALYSIS AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_FNAME,
    CUSTOMER_LNAME,
    CUSTOMER_SEGMENT,
    MARKET,
    ROUND(SUM(SALES),2) AS TOTAL_SALES,
    ROUND(SUM(ORDER_PROFIT_PER_ORDER),2) AS TOTAL_PROFIT,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(ORDER_ITEM_QUANTITY) AS TOTAL_QUANTITY_SOLD,
    ROUND(SUM(SALES)/COUNT(DISTINCT ORDER_ID),2) AS AVG_ORDER_VALUE
FROM DATACO_RAW
GROUP BY
    CUSTOMER_ID,
    CUSTOMER_FNAME,
    CUSTOMER_LNAME,
    CUSTOMER_SEGMENT,
    MARKET;



CREATE OR REPLACE VIEW VW_MARKET_ANALYSIS AS
SELECT MARKET,
ORDER_REGION,
ORDER_COUNTRY,
ROUND(SUM(SALES),2) AS TOTAL_SALES,
    ROUND(SUM(ORDER_PROFIT_PER_ORDER),2) AS TOTAL_PROFIT,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(ORDER_ITEM_QUANTITY) AS TOTAL_QUANTITY_SOLD,
    ROUND(SUM(SALES)/COUNT(DISTINCT ORDER_ID),2) AS AVG_ORDER_VALUE
FROM DATACO_RAW
GROUP BY
MARKET,
ORDER_REGION,
ORDER_COUNTRY;



CREATE OR REPLACE VIEW VW_SHIPPING_ANALYSIS AS
SELECT SHIPPING_MODE,
ROUND(AVG(SHIPPING_DELAY),2)AS AVG_SHIPPING_DELAY,
DELIVERY_STATUS,
ROUND(SUM(SALES),2) AS TOTAL_SALES,
    ROUND(SUM(ORDER_PROFIT_PER_ORDER),2) AS TOTAL_PROFIT,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
SUM(CASE WHEN DELIVERY_STATUS = 'Late delivery' THEN 1 ELSE 0 END) AS LATE_DELIVERY_COUNT
FROM DATACO_RAW
 GROUP BY SHIPPING_MODE,DELIVERY_STATUS;



CREATE OR REPLACE VIEW VW_DISCOUNT_PROFIT_ANALYSIS AS
SELECT 
ORDER_ITEM_DISCOUNT_RATE,
ROUND(SUM(SALES),2) AS TOTAL_SALES,
ROUND(SUM(ORDER_PROFIT_PER_ORDER),2) AS TOTAL_PROFIT,
COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
SUM(ORDER_ITEM_QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM DATACO_RAW GROUP BY ORDER_ITEM_DISCOUNT_RATE;



CREATE OR REPLACE VIEW VW_PRODUCT_PERFORMANCE AS
SELECT
    PRODUCT_NAME,
    CATEGORY_NAME,
    DEPARTMENT_NAME,
    ROUND(SUM(SALES),2) AS TOTAL_SALES,
    ROUND(SUM(ORDER_PROFIT_PER_ORDER),2) AS TOTAL_PROFIT,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(ORDER_ITEM_QUANTITY) AS TOTAL_QUANTITY_SOLD,
    ROUND(AVG(ORDER_ITEM_DISCOUNT_RATE),2) AS AVERAGE_DISCOUNT_RATE
FROM DATACO_RAW
GROUP BY
    PRODUCT_NAME,
    CATEGORY_NAME,
    DEPARTMENT_NAME;



CREATE OR REPLACE VIEW VW_ORDER_ANALYSIS AS
SELECT
    ORDER_STATUS,
    ROUND(SUM(ORDER_PROFIT_PER_ORDER),2) AS TOTAL_PROFIT,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(SALES),2) AS TOTAL_SALES,
    SUM(ORDER_ITEM_QUANTITY) AS TOTAL_QUANTITY_SOLD,
    ROUND(SUM(SALES)/COUNT(DISTINCT ORDER_ID),2) AS AVG_ORDER_VALUE
FROM DATACO_RAW
GROUP BY
    ORDER_STATUS;
