
CREATE OR REPLACE VIEW VW_DELIVERY_KPIS AS
SELECT  
ROUND(COUNT(DISTINCT CASE WHEN Delivery_Status = 'Late delivery' THEN Order_Id END)/NULLIF(COUNT(DISTINCT Order_Id),0)*100,2) AS LATE_DELIVERY_RATE,
ROUND(COUNT(DISTINCT CASE WHEN Delivery_Status = 'Shipping on time' THEN Order_Id END)/NULLIF(COUNT(DISTINCT Order_Id),0)*100,2) AS ON_TIME_RATE,
ROUND(AVG(Shipping_Delay),2) AS AVERAGE_SHIPPING_DELAY,
(SELECT COUNT(DISTINCT Order_Id) FROM   DATACO_RAW WHERE Shipping_Delay > 0) AS HIGH_RISK_ORDERS
FROM
DATACO_RAW;



CREATE OR REPLACE VIEW Late_Delivery_Rate_by_Shipping_Mode AS
SELECT 
ROUND(COUNT(DISTINCT CASE WHEN Delivery_Status = 'Late delivery' THEN Order_Id END)/NULLIF(COUNT(DISTINCT Order_Id),0)*100,2) AS LATE_DELIVERY_RATE,
Shipping_Mode
FROM DATACO_RAW GROUP BY Shipping_Mode;



CREATE OR REPLACE VIEW AVG_DELAYBYMARKET AS
SELECT 
ROUND(AVG(Shipping_Delay),2) AS AVG_SHIPPING_DELAY,
Market
FROM DATACO_RAW
GROUP BY Market;



CREATE OR REPLACE VIEW AVG_SHIPPING_DELAYBYMARKET AS
SELECT 
ROUND(COUNT(DISTINCT CASE WHEN Delivery_Status = 'Late delivery' THEN Order_Id END)/NULLIF(COUNT(DISTINCT Order_Id),0)*100,2) AS LATE_DELIVERY_RATE,
Category_Name
FROM DATACO_RAW GROUP BY Category_Name; 



CREATE OR REPLACE VIEW VW_ACTUAL_VS_SCHEDULED_SHIPPING AS
SELECT 
SHIPPING_MODE,
 ROUND(AVG(DAYS_FOR_SHIPPING_REAL), 2) AS AVG_ACTUAL_SHIPPING_DAYS,
ROUND(AVG(DAYS_FOR_SHIPMENT_SCHEDULED), 2) AS AVG_SCHEDULED_SHIPPING_DAYS
FROM DATACO_RAW
GROUP BY SHIPPING_MODE;



CREATE OR REPLACE VIEW Delivery_Risk_Analaysis AS
SELECT 
COUNT(DISTINCT Order_Id) AS ORDER_COUNT,
COUNT( DISTINCT CASE WHEN Shipping_Delay > 0 THEN Order_Id END) AS HIGH_RISK_ORDERS,
COUNT( DISTINCT CASE WHEN Shipping_Delay > 0 THEN Order_Id END)/NULLIF(COUNT(DISTINCT Order_Id),0) AS HIGH_RISK_RATE,
ROUND(AVG(Shipping_Delay),2) AS AVERAGE_SHIPPING_DELAY,
MARKET, SHIPPING_MODE
FROM 
DATACO_RAW GROUP BY MARKET, SHIPPING_MODE;



CREATE OR REPLACE VIEW Shipping_Delay_by_Month AS
SELECT 
ROUND(AVG(Shipping_Delay),2) AS AVG_SHIPING_DELAY,
Order_Month,
Order_Year
FROM DATACO_RAW GROUP BY Order_Month,Order_Year;


SELECT 
ROUND(AVG(Shipping_Delay),2) AS AVG_SHIPING_DELAY,
Order_Month,
Order_Year
FROM DATACO_RAW GROUP BY Order_Month,Order_Year;











