CREATE OR REPLACE TABLE DATACO_RAW (
    TYPE VARCHAR,
    DAYS_FOR_SHIPPING_REAL NUMBER,
    DAYS_FOR_SHIPMENT_SCHEDULED NUMBER,
    BENEFIT_PER_ORDER FLOAT,
    SALES_PER_CUSTOMER FLOAT,
    DELIVERY_STATUS VARCHAR,
    LATE_DELIVERY_RISK NUMBER,
   CATEGORY_ID NUMBER,CATEGORY_NAME VARCHAR,
    CUSTOMER_CITY VARCHAR,
    CUSTOMER_COUNTRY VARCHAR,
    CUSTOMER_FNAME VARCHAR,
    CUSTOMER_ID NUMBER,
    CUSTOMER_LNAME VARCHAR,
    CUSTOMER_SEGMENT VARCHAR,
    CUSTOMER_STATE VARCHAR,
    CUSTOMER_STREET VARCHAR,
    CUSTOMER_ZIPCODE FLOAT,
    DEPARTMENT_ID NUMBER,
    DEPARTMENT_NAME VARCHAR,

    LATITUDE FLOAT,
    LONGITUDE FLOAT,

    MARKET VARCHAR,

    ORDER_CITY VARCHAR,
    ORDER_COUNTRY VARCHAR,
    ORDER_CUSTOMER_ID NUMBER,

    ORDER_DATE TIMESTAMP,

    ORDER_ID NUMBER,

    ORDER_ITEM_CARDPROD_ID NUMBER,
    ORDER_ITEM_DISCOUNT FLOAT,
    ORDER_ITEM_DISCOUNT_RATE FLOAT,
    ORDER_ITEM_ID NUMBER,
    ORDER_ITEM_PRODUCT_PRICE FLOAT,
    ORDER_ITEM_PROFIT_RATIO FLOAT,
    ORDER_ITEM_QUANTITY NUMBER,

    SALES FLOAT,
    ORDER_ITEM_TOTAL FLOAT,
    ORDER_PROFIT_PER_ORDER FLOAT,

    ORDER_REGION VARCHAR,
    ORDER_STATE VARCHAR,
    ORDER_STATUS VARCHAR,

    PRODUCT_CARD_ID NUMBER,
    PRODUCT_CATEGORY_ID NUMBER,
    PRODUCT_NAME VARCHAR,
    PRODUCT_PRICE FLOAT,
    PRODUCT_STATUS NUMBER,

    SHIPPING_DATE TIMESTAMP,
    SHIPPING_MODE VARCHAR,

    ORDER_YEAR NUMBER,
    ORDER_MONTH VARCHAR,
    ORDER_QUARTER NUMBER,
    ORDER_DAY VARCHAR,

    SHIPPING_DELAY NUMBER

);

COPY INTO DATACO_RAW FROM @DATACO_STAGE FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);
